### ISSUE TITLE
Sidebar for event information

### ISSUE THREAD

**Issue by ajp4707** [nicholasamigo/BeHere#17]
As a novice user of BeHere, I want a frame that is separate from the Google Map that displays information about the "selected event" so that I can get all the info I need about the event.

### Acceptance Criteria
- [x] Google maps is offset to the left
- [ ] Sidebar displays default text "click on a marker to see details"
- [x] When clicking on a marker, sidebar gives the name and date of the event

### Tips
Will need to use HTML and CSS, and Angular Material can help with this "grid/column" format
https://material.angular.io/components/grid-list/examples
Steps (probably)
1. Put google map on left and some text on right. 
2. Need a js function to interface with Gmaps that updates the text on the right. Should be doable with "on-click" googlemaps functions.

### Resources:
- https://material.angular.io/components/grid-list/overview
- look at Gmap.component.ts

**Comment by ajp4707** [comment]
Update: @nicholasamigo need to 
-[ ] create new angular component within Gmap module. Make sure you cd to `gmap` before running `ng generate component modulenamehere`
-[ ] have this new module's html file read dummy data (name, date) and display on right side

**Comment by nicholasamigo** [comment]
Still need to leave a default message before clicking any events. The next step is to allow event creation and also work on the presentation of each event's information.
