### ISSUE TITLE
Condensed Event Card Implementation

### ISSUE THREAD

**Issue by nicholasamigo** [nicholasamigo/BeHere#55]
As a developer of BeHere, I want an event "card" container on the Map page of the BeHere website.

**Acceptance criteria**
- [x] Display more important variables of an event, including Title, Host, Address, Time, Date, and Number of Attendees.
- [x] Implement an "Info" button that, when clicked, opens the larger card for the event.
- [x] Implement an "Attend" button to confirm attendance at an event.

![IMG_2598 Large](https://user-images.githubusercontent.com/73868359/228963641-37be7f06-7128-4fec-96eb-247878961f65.jpeg)

**Comment by ajp4707** [comment]
Closed by #62
