### ISSUE TITLE
Implement Editable Condensed and Expanded Event Cards

### ISSUE THREAD

**Issue by nicholasamigo** [nicholasamigo/BeHere#58]
As a developer of BeHere, I want to be able to edit an event card in the "My Events" page.

**Acceptance criteria**
- [ ] Swap the "Attend" button with an "Edit" button on the Condensed Event Card.
- [ ] When the "Edit" button is clicked, create a popup of an editable Expanded Event Card with a movable event in the Gmap container.
- [ ] Create "Save" and "Cancel" buttons that appear in the editable Expanded Event Card.

![IMG_2599 Large](https://user-images.githubusercontent.com/73868359/228966860-4e551ab8-1431-4011-8909-1049ca79afc7.jpeg)

**Comment by ajp4707** [comment]
See #41 . This will be solved by the Card C commits
